### ISSUE TITLE
Maven Set Up

### ISSUE THREAD

**Issue by JaviCaballero96** [gree7/psm-planner#1]
Hello

I'm trying to launch the planner but the link to the settings.xml file in the README.me seems to be broken. I'll appreciate a new link since I can't compile without it.

Thanks in advance.

**Comment by gree7** [comment]
Hi,
I've added the settings.xml file directly in the repository.

**Comment by Mxc666** [comment]
Hello

I'm trying to build the planner, but when I set up the maven, some errors happened:

" [ERROR] Some problems were encountered while processing the PO
Ms:
[FATAL] Non-resolvable parent POM for FSM:FSM:0.0.1-SNAPSHOT: Could not find art
ifact cz.agents:atgparent:pom:1.0-SNAPSHOT in atg-repo (http://jones.felk.cvut.c
z/artifactory/repo) and 'parent.relativePath' points at wrong local POM @ line 8
, column 13"

Maybe it's the loss file of parent's pom? I don't know, hoping you answer. Thanks

Thanks in advance.
