### ISSUE TITLE
set up maven: parent pom

### ISSUE THREAD

**Issue by Mxc666** [gree7/psm-planner#3]
Hello

I'm trying to build the planner, but when I set up the maven, some errors happened:

" [ERROR] Some problems were encountered while processing the PO
Ms:
[FATAL] Non-resolvable parent POM for FSM:FSM:0.0.1-SNAPSHOT: Could not find art
ifact cz.agents:atgparent:pom:1.0-SNAPSHOT in atg-repo (http://jones.felk.cvut.c/
z/artifactory/repo) and 'parent.relativePath' points at wrong local POM @ line 8
, column 13"

Maybe it's the loss file of parent's pom? I don't know, hoping you answer. Thanks

Thanks in advance.

**Comment by gree7** [comment]
Unfortunately the servers at the university with the dependencies is gone for good. So there is not much I can do about it.
